apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: database
  labels:
    app: redis
    tier: database
    env: test00
spec:
  serviceName: "redis"
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6.2-alpine
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
          resources:
            limits:
              memory: "1Gi"
              cpu: "125m"
            requests:
              memory: "128Mi"
              cpu: "125m"
          command: ["redis-server", "--appendonly", "yes"]
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: database
  labels:
    app: redis
    tier: database
    env: test00
spec:
  clusterIP: None
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
