apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatch
  namespace: services
  labels:
    app: dispatch
    tier: backend
    env: test00
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatch
  template:
    metadata:
      labels:
        app: dispatch
    spec:
      containers:
        - name: dispatch
          image: "martin2020i/dispatch:v6.0.0"
          ports:
            - containerPort: 8080
          env:
            - name: AMQP_HOST
              value: "rabbitmq.database.svc.cluster.local"
            - name: DISPATCH_ERROR_PERCENT
              value: "5"
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - curl -f http://localhost:8080/health || exit 1
            initialDelaySeconds: 10
            periodSeconds: 3600 
            timeoutSeconds: 10
            failureThreshold: 1
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
      resources:
        requests:
          cpu: 100m       
          memory: 128Mi  
        limits:
          cpu: 100m 
          memory: 256Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: dispatch
  namespace: services
  labels:
    app: dispatch
    tier: backend
    env: test00
spec:
  selector:
    app: dispatch
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
