apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: services
  labels:
    app: payment
    tier: backend
    env: test00
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: "martin2020i/payment:v6.0.0"
          ports:
            - containerPort: 8080
          env:
            - name: AMQP_HOST
              value: "amqp://rabbitmq.database.svc.cluster.local:5672"
            - name: PAYMENT_GATEWAY
              value: "https://www.worldpay.com"
            - name: CART_HOST
              value: "http://cart:8080"
            - name: USER_HOST
              value: "http://user:8080"
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "curl -H 'X-INSTANA-SYNTHETIC: 1' -f http://localhost:8080/health"
            initialDelaySeconds: 10
            periodSeconds: 3600   
            timeoutSeconds: 10
            failureThreshold: 1
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: services
  labels:
    app: payment
    tier: backend
    env: test00
spec:
  selector:
    app: payment
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
