apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: services
  labels:
    app: payment
    tier: backend
    env: test00
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: "martin2020i/payment:v6.0.0"
          ports:
            - containerPort: 8080
          env:
            - name: AMQP_HOST
              value: "amqp://rabbitmq.database.svc.cluster.local:5672"
            - name: PAYMENT_GATEWAY
              value: "https://www.worldpay.com"
            - name: CART_HOST
              value: "cart"
            - name: USER_HOST
              value: "user"
            - name: INSTANA_AGENT_HOST
              value: "instana-agent"
            - name: INSTANA_AGENT_ENDPOINT_PORT
              value: "42699" 
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: services
  labels:
    app: payment
    tier: backend
    env: test00
spec:
  selector:
    app: payment
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
